import { createContext, useContext, useState, ReactNode, useCallback, useMemo } from "react";

export type Language = "EN" | "FR" | "ES" | "NL" | "JP" | "ET" | "GE" | "PT" | "AR" | "SQ" | "ID" | "SW";
export type Currency = "USD" | "EUR" | "GBP" | "JPY" | "GEL" | "ETB" | "COP" | "ALL" | "IDR" | "TZS";

interface SettingsContextType {
  language: Language;
  currency: Currency;
  setLanguage: (lang: Language) => void;
  setCurrency: (curr: Currency) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  formatPrice: (price: number) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "nav.find_guide": "Find a Guide",
    "nav.world_map": "World Map",
    "nav.hidden_gems": "Hidden Gems",
    "nav.how_it_works": "How it Works",
    "nav.sign_in": "Sign In",
    "hero.badge": "The New Way to Travel",
    "hero.title.1": "Travel like a ",
    "hero.title.highlight": "local",
    "hero.title.2": ", not a tourist.",
    "hero.subtitle": "Connect with verified local guides who offer hidden gem experiences — places, trails, and moments that don't appear in any guidebook.",
    "hero.cta": "Start Exploring",
    "hero.social": "Joined by 12k+ travellers",
    "features.verified.title": "Verified Guides",
    "features.verified.desc": "Every guide is personally interviewed and vetted for local knowledge, safety, and storytelling ability.",
    "features.gems.title": "Hidden Gems",
    "features.gems.desc": "Access places that aren't on Instagram or in guidebooks. True off-the-beaten-path experiences.",
    "features.ethical.title": "Ethical Travel",
    "features.ethical.desc": "Your money goes directly to local communities, supporting heritage preservation and sustainable tourism.",
    "featured.badge": "Meet the Experts",
    "featured.title.1": "Our Featured ",
    "featured.title.highlight": "Local Guides",
    "featured.title.2": "",
    "featured.cta": "View All Guides",
    "cta.title": "Ready for a story worth telling?",
    "cta.subtitle": "Join thousands of travellers who have discovered the world through the eyes of those who call it home.",
    "cta.button": "Find Your Perfect Match",
    "footer.desc": "Connecting travellers with verified local guides who offer hidden gem experiences. Travel like a local, not a tourist.",
    "footer.platform": "Platform",
    "footer.support": "Support",
    "footer.rights": "© 2026 Localens. All rights reserved.",
    "common.back_home": "Back to Home",
    "common.verified": "Verified",
    "common.reviews": "reviews",
    "common.from": "From",
    "common.person": "person",
    "common.book_now": "Book Now",
    "common.view_profile": "View Profile",
    "common.apply_guide": "Apply to be a guide",
    "find.title": "Where are you headed?",
    "find.subtitle": "Select a country to discover local experts who know the hidden trails and secret stories of their homeland.",
    "find.guides_count": "{count} Guides",
    "find.another_country": "Choose another country",
    "find.showing": "Showing {count} verified local experts in {country}.",
    "profile.verified": "Verified Local Expert",
    "profile.reviews": "({count} reviews)",
    "profile.from_person": "{price} / person",
    "profile.book": "Book this guide",
    "profile.about": "About your guide",
    "profile.languages": "Languages",
    "profile.experience": "Experience",
    "profile.experience_years": "{years} Years",
    "profile.expertise": "Expertise",
    "profile.promise_badge": "{name}'s Personal Guarantee",
    "profile.packages": "Curated Experiences",
    "profile.most_popular": "Most Popular",
    "profile.select_tour": "Select this tour",
    "profile.stories": "Traveller Stories",
    "profile.secure_booking": "Secure Your Experience",
    "profile.select_package": "Choose a package",
    "profile.date": "Date",
    "profile.travellers": "Travellers",
    "profile.person": "Person",
    "profile.people": "People",
    "profile.full_name": "Full Name",
    "profile.email": "Email Address",
    "profile.message": "Message to guide (optional)...",
    "profile.confirm_pay": "Confirm & Pay Securely",
    "profile.free_cancel": "Free cancellation up to 48h",
    "profile.confirmed_within": "Confirmed within 24h",
    "profile.powered_by": "Powered by Stripe",
    "help.title": "Help Centre",
    "help.subtitle": "Everything you need to know about using Localens",
    "help.still_questions": "Still have questions?",
    "help.email_us": "Email us at support@localens.com",
    "help.email_support": "Email Support",
    "footer.guide_app": "Guide Application",
    "footer.help_centre": "Help Centre",
    "footer.safety": "Safety Guidelines",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "chat.title": "AI Match Assistant",
    "chat.subtitle": "Powered by Localens AI",
    "chat.welcome": "Welcome to Localens. I'm your AI Match assistant. Describe your dream trip, and I'll find the perfect local guide to show you the hidden gems most travellers never see.",
    "chat.placeholder": "Describe your dream trip...",
    "chat.suggested.1": "Hidden gems in Lebanon",
    "chat.suggested.2": "Off the beaten path in Japan",
    "chat.suggested.3": "Ancient ruins no one visits",
    "chat.suggested.4": "Most unique guide on the platform",
    "chat.suggested.5": "I want to sleep somewhere with no WiFi",
    "gems.badge": "Undocumented",
    "gems.title.1": "Places you won't find ",
    "gems.title.highlight": "anywhere",
    "gems.title.2": " else",
    "gems.subtitle": "These are real places. They have no Instagram hashtag. They don't appear in Google's top results. The only way to reach them is through someone who lives there.",
    "gems.mystery_title": "The mystery is the point.",
    "gems.mystery_desc": "We don't provide coordinates. We don't provide names. We provide the connection to the people who hold the keys to these places.",
    "gems.cta": "Find a local guide who knows the way",
    "how.step.1.title": "Tell us where you're going",
    "how.step.1.desc": "Choose a country or describe your dream experience to our AI. Whether it's 'stargazing in a cedar forest' or 'secret medina foundries', we listen to the details.",
    "how.step.2.title": "We match you with a local",
    "how.step.2.desc": "Our AI and editorial team match you with a verified guide who knows places others don't. We prioritize deep local knowledge and storytelling ability.",
    "how.step.3.title": "Explore the hidden gems",
    "how.step.3.desc": "Your guide takes you somewhere that doesn't exist on any tourist map. No hashtags, no crowds—just you and a story worth telling.",
    "how.step.4.title": "Book securely. Travel freely.",
    "how.step.4.desc": "Pay through Localens. Free cancellation up to 48h. Guide confirmed within 24h. We handle the logistics so you can focus on the moment.",
    "how.previous": "Previous",
    "how.next": "Next",
    "how.ready": "Ready? Find your guide",
    "how.try_live": "Try it live",
    "how.search_placeholder": "e.g. 'I want to see the Milky Way in Lebanon'",
    "how.search": "Search",
    "how.all_set": "You're all set.",
    "how.all_set_desc": "Your booking is protected, your guide is ready, and your adventure is about to begin.",
    "map.title.1": "Explore the ",
    "map.title.highlight": "World",
    "map.search_placeholder": "Search a country (e.g. Japan, Lebanon)...",
    "map.active_guide": "Active Guide",
    "map.coming_soon": "Coming Soon",
    "map.coming_soon_desc": "Guide coming soon to this region.",
    "bashir.bio": "Born in the rugged mountains of Chouf, Bashir has spent two decades mapping the undocumented trails of Lebanon. He specializes in high-altitude forest ecosystems and coastal geological wonders. His deep connection to the land allows him to navigate areas that remain invisible to mainstream tourism. Bashir is a passionate advocate for environmental preservation in the Levant.",
    "bashir.promise": "I promise you will stand somewhere in Lebanon that no other tourist has visited that day.",
    "bashir.speciality": "Hidden waterfalls, sea caves, Akkar forests, stargazing",
    "bashir.tour.1.name": "The Akkar Deep Forest Expedition",
    "bashir.tour.1.included.1": "Transport",
    "bashir.tour.1.included.2": "Traditional Lunch",
    "bashir.tour.1.included.3": "Photography Tips",
    "bashir.tour.2.name": "Coastal Caves & Salt Pans",
    "bashir.tour.2.included.1": "Boat Access",
    "bashir.tour.2.included.2": "Snacks",
    "bashir.tour.2.included.3": "Local History Guide"
  },
  FR: {
    "nav.find_guide": "Trouver un guide",
    "nav.world_map": "Carte du monde",
    "nav.hidden_gems": "Trésors cachés",
    "nav.how_it_works": "Comment ça marche",
    "nav.sign_in": "Se connecter",
    "hero.badge": "La nouvelle façon de voyager",
    "hero.title.1": "Voyagez comme un ",
    "hero.title.highlight": "local",
    "hero.title.2": ", pas comme un touriste.",
    "hero.subtitle": "Connectez-vous avec des guides locaux vérifiés qui proposent des expériences uniques — des lieux, des sentiers et des moments qui ne figurent dans aucun guide.",
    "hero.cta": "Commencer l'exploration",
    "hero.social": "Rejoint par plus de 12k voyageurs",
    "features.verified.title": "Guides vérifiés",
    "features.verified.desc": "Chaque guide est personnellement interviewé et évalué pour ses connaissances locales, sa sécurité et sa capacité à raconter des histoires.",
    "features.gems.title": "Trésors cachés",
    "features.gems.desc": "Accédez à des endroits qui ne sont pas sur Instagram ou dans les guides. De véritables expériences hors des sentiers battus.",
    "features.ethical.title": "Voyage éthique",
    "features.ethical.desc": "Votre argent va directement aux communautés locales, soutenant la préservation du patrimoine et le tourisme durable.",
    "featured.badge": "Rencontrez les experts",
    "featured.title.1": "Nos ",
    "featured.title.highlight": "guides locaux",
    "featured.title.2": " en vedette",
    "featured.cta": "Voir tous les guides",
    "cta.title": "Prêt pour une histoire qui vaut la peine d'être racontée ?",
    "cta.subtitle": "Rejoignez des milliers de voyageurs qui ont découvert le monde à travers les yeux de ceux qui y vivent.",
    "cta.button": "Trouvez votre partenaire idéal",
    "footer.desc": "Connecter les voyageurs avec des guides locaux vérifiés qui proposent des expériences uniques. Voyagez comme un local, pas comme un touriste.",
    "footer.platform": "Plateforme",
    "footer.support": "Support",
    "footer.rights": "© 2026 Localens. Tous droits réservés.",
    "common.back_home": "Retour à l'accueil",
    "common.verified": "Vérifié",
    "common.reviews": "avis",
    "common.from": "À partir de",
    "common.person": "personne",
    "common.book_now": "Réserver maintenant",
    "common.view_profile": "Voir le profil",
    "common.apply_guide": "Devenir guide",
    "find.title": "Où allez-vous ?",
    "find.subtitle": "Sélectionnez un pays pour découvrir des experts locaux qui connaissent les sentiers cachés et les histoires secrètes de leur patrie.",
    "find.guides_count": "{count} Guides",
    "find.another_country": "Choisir un autre pays",
    "find.showing": "Affichage de {count} experts locaux vérifiés en {country}.",
    "profile.verified": "Expert Local Vérifié",
    "profile.reviews": "({count} avis)",
    "profile.from_person": "{price} / personne",
    "profile.book": "Réserver ce guide",
    "profile.about": "À propos de votre guide",
    "profile.languages": "Langues",
    "profile.experience": "Expérience",
    "profile.experience_years": "{years} Ans",
    "profile.expertise": "Expertise",
    "profile.promise_badge": "Garantie Personnelle de {name}",
    "profile.packages": "Expériences Curieuses",
    "profile.most_popular": "Le Plus Populaire",
    "profile.select_tour": "Sélectionner ce tour",
    "profile.stories": "Histoires de Voyageurs",
    "profile.secure_booking": "Sécurisez Votre Expérience",
    "profile.select_package": "Choisir un forfait",
    "profile.date": "Date",
    "profile.travellers": "Voyageurs",
    "profile.person": "Personne",
    "profile.people": "Personnes",
    "profile.full_name": "Nom Complet",
    "profile.email": "Adresse E-mail",
    "profile.message": "Message au guide (optionnel)...",
    "profile.confirm_pay": "Confirmer et Payer en Toute Sécurité",
    "profile.free_cancel": "Annulation gratuite jusqu'à 48h",
    "profile.confirmed_within": "Confirmé sous 24h",
    "profile.powered_by": "Sécurisé par Stripe",
    "help.title": "Centre d'Aide",
    "help.subtitle": "Tout ce que vous devez savoir sur l'utilisation de Localens",
    "help.still_questions": "Vous avez encore des questions ?",
    "help.email_us": "Envoyez-nous un e-mail à support@localens.com",
    "help.email_support": "Support par E-mail",
    "footer.guide_app": "Candidature Guide",
    "footer.help_centre": "Centre d'Aide",
    "footer.safety": "Consignes de Sécurité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.privacy": "Politique de Confidentialité",
    "chat.title": "Assistant de Match IA",
    "chat.subtitle": "Propulsé par Localens IA",
    "chat.welcome": "Bienvenue chez Localens. Je suis votre assistant de match IA. Décrivez votre voyage de rêve, et je trouverai le guide local parfait pour vous montrer les joyaux cachés que la plupart des voyageurs ne voient jamais.",
    "chat.placeholder": "Décrivez votre voyage de rêve...",
    "chat.suggested.1": "Joyaux cachés au Liban",
    "chat.suggested.2": "Hors des sentiers battus au Japon",
    "chat.suggested.3": "Ruines antiques que personne ne visite",
    "chat.suggested.4": "Guide le plus unique sur la plateforme",
    "chat.suggested.5": "Je veux dormir quelque part sans WiFi",
    "gems.badge": "Non documenté",
    "gems.title.1": "Des endroits que vous ne trouverez ",
    "gems.title.highlight": "nulle part",
    "gems.title.2": " ailleurs",
    "gems.subtitle": "Ce sont de vrais endroits. Ils n'ont pas de hashtag Instagram. Ils n'apparaissent pas dans les meilleurs résultats de Google. La seule façon de les atteindre est de passer par quelqu'un qui y vit.",
    "gems.mystery_title": "Le mystère est le but.",
    "gems.mystery_desc": "Nous ne fournissons pas de coordonnées. Nous ne fournissons pas de noms. Nous fournissons la connexion aux personnes qui détiennent les clés de ces lieux.",
    "gems.cta": "Trouver un guide local qui connaît le chemin",
    "how.step.1.title": "Dites-nous où vous allez",
    "how.step.1.desc": "Choisissez un pays ou décrivez votre expérience de rêve à notre IA. Qu'il s'agisse d'observer les étoiles dans une forêt de cèdres ou de découvrir des fonderies secrètes dans la médina, nous écoutons les détails.",
    "how.step.2.title": "Nous vous mettons en relation avec un local",
    "how.step.2.desc": "Notre IA et notre équipe éditoriale vous mettent en relation avec un guide vérifié qui connaît des endroits que les autres ignorent. Nous privilégions une connaissance locale approfondie et une capacité de narration.",
    "how.step.3.title": "Explorez les joyaux cachés",
    "how.step.3.desc": "Votre guide vous emmène dans un endroit qui n'existe sur aucune carte touristique. Pas de hashtags, pas de foules — juste vous et une histoire qui vaut la peine d'être racontée.",
    "how.step.4.title": "Réservez en toute sécurité. Voyagez librement.",
    "how.step.4.desc": "Payez via Localens. Annulation gratuite jusqu'à 48h. Guide confirmé sous 24h. Nous gérons la logistique pour que vous puissiez vous concentrer sur le moment présent.",
    "how.previous": "Précédent",
    "how.next": "Suivant",
    "how.ready": "Prêt ? Trouvez votre guide",
    "how.try_live": "Essayez-le en direct",
    "how.search_placeholder": "ex: 'Je veux voir la Voie Lactée au Liban'",
    "how.search": "Rechercher",
    "how.all_set": "Vous êtes prêt.",
    "how.all_set_desc": "Votre réservation est protégée, votre guide est prêt et votre aventure est sur le point de commencer.",
    "map.title.1": "Explorez le ",
    "map.title.highlight": "Monde",
    "map.search_placeholder": "Rechercher un pays (ex: Japon, Liban)...",
    "map.active_guide": "Guide Actif",
    "map.coming_soon": "Bientôt Disponible",
    "map.coming_soon_desc": "Guide bientôt disponible dans cette région.",
    "bashir.bio": "Né dans les montagnes escarpées du Chouf, Bashir a passé deux décennies à cartographier les sentiers non documentés du Liban. Il se spécialise dans les écosystèmes forestiers de haute altitude et les merveilles géologiques côtières. Son lien profond avec la terre lui permet de naviguer dans des zones qui restent invisibles pour le tourisme grand public. Bashir est un fervent défenseur de la préservation de l'environnement au Levant.",
    "bashir.promise": "Je vous promets que vous vous tiendrez quelque part au Liban qu'aucun autre touriste n'aura visité ce jour-là.",
    "bashir.speciality": "Cascades cachées, grottes marines, forêts du Akkar, observation des étoiles",
    "bashir.tour.1.name": "L'expédition en forêt profonde du Akkar",
    "bashir.tour.1.included.1": "Transport",
    "bashir.tour.1.included.2": "Déjeuner traditionnel",
    "bashir.tour.1.included.3": "Conseils en photographie",
    "bashir.tour.2.name": "Grottes côtières et marais salants",
    "bashir.tour.2.included.1": "Accès en bateau",
    "bashir.tour.2.included.2": "Collations",
    "bashir.tour.2.included.3": "Guide d'histoire locale"
  },
  ES: {
    "nav.find_guide": "Buscar un guía",
    "nav.world_map": "Mapa mundial",
    "nav.hidden_gems": "Joyas ocultas",
    "nav.how_it_works": "Cómo funciona",
    "nav.sign_in": "Iniciar sesión",
    "hero.badge": "La nueva forma de viajar",
    "hero.title.1": "Viaja como un ",
    "hero.title.highlight": "local",
    "hero.title.2": ", no como un turista.",
    "hero.subtitle": "Conéctate con guías locales verificados que ofrecen experiencias únicas: lugares, senderos y momentos que no aparecen en ninguna guía.",
    "hero.cta": "Empezar a explorar",
    "hero.social": "Se han unido más de 12k viajeros",
    "features.verified.title": "Guías verificados",
    "features.verified.desc": "Cada guía es entrevistado personalmente y evaluado por su conocimiento local, seguridad y capacidad narrativa.",
    "features.gems.title": "Joyas ocultas",
    "features.gems.desc": "Accede a lugares que no están en Instagram ni en las guías. Experiencias auténticas fuera de lo común.",
    "features.ethical.title": "Viaje ético",
    "features.ethical.desc": "Tu dinero va directamente a las comunidades locales, apoyando la preservación del patrimonio y el turismo sostenible.",
    "featured.badge": "Conoce a los expertos",
    "featured.title.1": "Nuestros ",
    "featured.title.highlight": "guías locales",
    "featured.title.2": " destacados",
    "featured.cta": "Ver todos los guías",
    "cta.title": "¿Listo para una historia que valga la pena contar?",
    "cta.subtitle": "Únete a miles de viajeros que han descubierto el mundo a través de los ojos de quienes lo llaman hogar.",
    "cta.button": "Encuentra tu pareja ideal",
    "footer.desc": "Conectando viajeros con guías locales verificados que ofrecen experiencias únicas. Viaja como un local, no como un turista.",
    "footer.platform": "Plataforma",
    "footer.support": "Soporte",
    "footer.rights": "© 2026 Localens. Todos los derechos reservados.",
    "common.back_home": "Volver al inicio",
    "common.verified": "Verificado",
    "common.reviews": "reseñas",
    "common.from": "Desde",
    "common.person": "persona",
    "common.book_now": "Reservar ahora",
    "common.view_profile": "Ver perfil",
    "common.apply_guide": "Postular como guía",
    "chat.title": "Asistente de IA",
    "chat.subtitle": "Tu guía local de IA",
    "chat.welcome": "¡Hola! Soy tu asistente de IA de Localens. Puedo ayudarte a encontrar el guía perfecto o descubrir joyas ocultas. ¿A dónde te gustaría ir?",
    "chat.placeholder": "Pregúntame cualquier cosa...",
    "chat.suggested.1": "¿Quién es el mejor guía para el Líbano?",
    "chat.suggested.2": "Encuéntrame una joya oculta en Japón",
    "chat.suggested.3": "¿Cómo funciona Localens?",
    "chat.suggested.4": "Muéstrame guías en Marruecos",
    "chat.suggested.5": "¿Qué incluye el tour de Bashir?",
    "gems.badge": "No documentado",
    "gems.title.1": "Lugares que no encontrarás en ",
    "gems.title.highlight": "ningún otro",
    "gems.title.2": " lugar",
    "gems.subtitle": "Estos son lugares reales. No tienen hashtag en Instagram. No aparecen en los primeros resultados de Google. La única forma de llegar a ellos es a través de alguien que viva allí.",
    "gems.mystery_title": "El misterio es el punto.",
    "gems.mystery_desc": "No proporcionamos coordenadas. No proporcionamos nombres. Proporcionamos la conexión con las personas que tienen las llaves de estos lugares.",
    "gems.cta": "Encuentra un guía local que conozca el camino",
    "how.step.1.title": "Cuéntanos a dónde vas",
    "how.step.1.desc": "Elige un país o describe tu experiencia soñada a nuestra IA. Ya sea 'observar estrellas en un bosque de cedros' o 'fundiciones secretas en la medina', escuchamos los detalles.",
    "how.step.2.title": "Te emparejamos con un local",
    "how.step.2.desc": "Nuestro equipo editorial y de IA te empareja con un guía verificado que conoce lugares que otros no. Priorizamos el conocimiento local profundo y la capacidad narrativa.",
    "how.step.3.title": "Explora las joyas ocultas",
    "how.step.3.desc": "Tu guía te lleva a algún lugar que no existe en ningún mapa turístico. Sin hashtags, sin multitudes, solo tú y una historia que vale la pena contar.",
    "how.step.4.title": "Reserva de forma segura. Viaja libremente.",
    "how.step.4.desc": "Paga a través de Localens. Cancelación gratuita hasta 48h. Guía confirmado en 24h. Nosotros nos encargamos de la logística para que tú te enfoques en el momento.",
    "how.previous": "Anterior",
    "how.next": "Siguiente",
    "how.ready": "¿Listo? Encuentra tu guía",
    "how.try_live": "Pruébalo en vivo",
    "how.search_placeholder": "ej. 'Quiero ver la Vía Láctea en el Líbano'",
    "how.search": "Buscar",
    "how.all_set": "Todo listo.",
    "how.all_set_desc": "Tu reserva está protegida, tu guía está listo y tu aventura está a punto de comenzar.",
    "map.title.1": "Explora el ",
    "map.title.highlight": "Mundo",
    "map.search_placeholder": "Busca un país (ej. Japón, Líbano)...",
    "map.active_guide": "Guía Activo",
    "map.coming_soon": "Próximamente",
    "map.coming_soon_desc": "Guía próximamente en esta región.",
    "bashir.bio": "Nacido en las escarpadas montañas de Chouf, Bashir ha pasado dos décadas mapeando los senderos no documentados del Líbano. Se especializa en ecosistemas forestales de gran altitud y maravillas geológicas costeras. Su profunda conexión con la tierra le permite navegar por áreas que permanecen invisibles para el turismo convencional. Bashir es un apasionado defensor de la preservación del medio ambiente en el Levante.",
    "bashir.promise": "Te prometo que estarás en algún lugar del Líbano que ningún otro turista haya visitado ese día.",
    "bashir.speciality": "Cascadas ocultas, cuevas marinas, bosques de Akkar, observación de estrellas",
    "bashir.tour.1.name": "La expedición al bosque profundo de Akkar",
    "bashir.tour.1.included.1": "Transporte",
    "bashir.tour.1.included.2": "Almuerzo tradicional",
    "bashir.tour.1.included.3": "Consejos de fotografía",
    "bashir.tour.2.name": "Cuevas costeras y salinas",
    "bashir.tour.2.included.1": "Acceso en barco",
    "bashir.tour.2.included.2": "Aperitivos",
    "bashir.tour.2.included.3": "Guía de historia local"
  },
  NL: {
    "nav.find_guide": "Vind een gids",
    "nav.world_map": "Wereldkaart",
    "nav.hidden_gems": "Verborgen parels",
    "nav.how_it_works": "Hoe het werkt",
    "nav.sign_in": "Inloggen",
    "hero.badge": "De nieuwe manier van reizen",
    "hero.title.1": "Reis als een ",
    "hero.title.highlight": "local",
    "hero.title.2": ", niet als een toerist.",
    "hero.subtitle": "Maak contact met geverifieerde lokale gidsen die unieke ervaringen bieden — plekken, paden en momenten die in geen enkele reisgids staan.",
    "hero.cta": "Begin met ontdekken",
    "hero.social": "Al 12k+ reizigers gingen je voor",
    "features.verified.title": "Geverifieerde gidsen",
    "features.verified.desc": "Elke gids wordt persoonlijk geïnterviewd en gescreend op lokale kennis, veiligheid en vertelkunst.",
    "features.gems.title": "Verborgen parels",
    "features.gems.desc": "Bezoek plekken die niet op Instagram of in reisgidsen staan. Echte off-the-beaten-path ervaringen.",
    "features.ethical.title": "Ethisch reizen",
    "features.ethical.desc": "Je geld gaat rechtstreeks naar lokale gemeenschappen, wat erfgoedbehoud en duurzaam toerisme ondersteunt.",
    "featured.badge": "Ontmoet de experts",
    "featured.title.1": "Onze uitgelichte ",
    "featured.title.highlight": "lokale gidsen",
    "featured.title.2": "",
    "featured.cta": "Bekijk alle gidsen",
    "cta.title": "Klaar voor een verhaal dat het vertellen waard is?",
    "cta.subtitle": "Sluit je aan bij duizenden reizigers die de wereld hebben ontdekt door de ogen van de mensen die er wonen.",
    "cta.button": "Vind je perfecte match",
    "footer.desc": "Reizigers verbinden met geverifieerde lokale gidsen die unieke ervaringen bieden. Reis als een local, niet als een toerist.",
    "footer.platform": "Platform",
    "footer.support": "Ondersteuning",
    "footer.rights": "© 2026 Localens. Alle rechten voorbehouden.",
    "common.back_home": "Terug naar Home",
    "common.verified": "Geverifieerd",
    "common.reviews": "beoordelingen",
    "common.from": "Vanaf",
    "common.person": "persoon",
    "common.book_now": "Nu boeken",
    "common.view_profile": "Bekijk profiel",
    "common.apply_guide": "Word een gids"
  },
  JP: {
    "nav.find_guide": "ガイドを探す",
    "nav.world_map": "世界地図",
    "nav.hidden_gems": "穴場スポット",
    "nav.how_it_works": "仕組み",
    "nav.sign_in": "サインイン",
    "hero.badge": "新しい旅のカタチ",
    "hero.title.1": "観光客ではなく、",
    "hero.title.highlight": "ローカル",
    "hero.title.2": "のように旅をしよう。",
    "hero.subtitle": "ガイドブックには載っていない場所、道、瞬間を提供する、認証済みの現地ガイドとつながりましょう。",
    "hero.cta": "探索を始める",
    "hero.social": "1万2千人以上の旅行者が参加中",
    "features.verified.title": "認証済みガイド",
    "features.verified.desc": "すべてのガイドは、現地の知識、安全性、ストーリーテリング能力について、個人的な面接と審査を受けています。",
    "features.gems.title": "穴場スポット",
    "features.gems.desc": "Instagramやガイドブックには載っていない場所にアクセス。真のオフ・ザ・ビートン・パス体験を。",
    "features.ethical.title": "エシカルな旅",
    "features.ethical.desc": "あなたの支払ったお金は直接現地のコミュニティに届き、文化遺産の保護や持続可能な観光を支援します。",
    "featured.badge": "エキスパートに会う",
    "featured.title.1": "注目の",
    "featured.title.highlight": "現地ガイド",
    "featured.title.2": "",
    "featured.cta": "すべてのガイドを見る",
    "cta.title": "語る価値のある物語の準備はいいですか？",
    "cta.subtitle": "その土地を故郷と呼ぶ人々の目を通して世界を発見した、何千人もの旅行者の仲間入りをしましょう。",
    "cta.button": "最高のパートナーを見つける",
    "footer.desc": "観光客ではなくローカルのように旅をする。認証済みの現地ガイドと旅行者をつなぎ、穴場体験を提供します。",
    "footer.platform": "プラットフォーム",
    "footer.support": "サポート",
    "footer.rights": "© 2026 Localens. All rights reserved.",
    "common.back_home": "ホームに戻る",
    "common.verified": "認証済み",
    "common.reviews": "件のレビュー",
    "common.from": "から",
    "common.person": "人",
    "common.book_now": "今すぐ予約",
    "common.view_profile": "プロフィールを見る",
    "common.apply_guide": "ガイドに応募する"
  },
  ET: {
    "nav.find_guide": "አስጎብኚ ፈልግ",
    "nav.world_map": "የዓለም ካርታ",
    "nav.hidden_gems": "የተደበቁ ቦታዎች",
    "nav.how_it_works": "እንዴት እንደሚሰራ",
    "nav.sign_in": "ግባ",
    "hero.badge": "አዲሱ የጉዞ መንገድ",
    "hero.title.1": "እንደ ቱሪስት ሳይሆን እንደ ",
    "hero.title.highlight": "አካባቢው",
    "hero.title.2": " ሰው ተጓዙ።",
    "hero.subtitle": "በየትኛውም የጉዞ መጽሐፍ ውስጥ የማይገኙ ቦታዎችን፣ መንገዶችን እና ትዝታዎችን የሚያቀርቡ ከተረጋገጡ የአካባቢ አስጎብኚዎች ጋር ይገናኙ።",
    "hero.cta": "መጎብኘት ጀምር",
    "hero.social": "ከ12 ሺህ በላይ ተጓዦች ተቀላቅለዋል",
    "features.verified.title": "የተረጋገጡ አስጎብኚዎች",
    "features.verified.desc": "እያንዳንዱ አስጎብኚ ስለ አካባቢው እውቀት፣ ደህንነት እና ታሪክ የመናገር ችሎታ በአካል ተገምግሟል።",
    "features.gems.title": "የተደበቁ ቦታዎች",
    "features.gems.desc": "በኢንስታግራም ወይም በጉዞ መጽሐፍት ላይ የማይገኙ ቦታዎችን ያግኙ። እውነተኛ የጉዞ ልምዶች።",
    "features.ethical.title": "ሥነ-ምግባራዊ ጉዞ",
    "features.ethical.desc": "ገንዘብዎ በቀጥታ ለአካባቢው ማህበረሰቦች ይሄዳል፣ ይህም ቅርሶችን ለመጠበቅ እና ዘላቂ ቱሪዝምን ይደግፋል።",
    "featured.badge": "ባለሙያዎቹን ያግኙ",
    "featured.title.1": "የእኛ ምርጥ ",
    "featured.title.highlight": "የአካባቢ አስጎብኚዎች",
    "featured.title.2": "",
    "featured.cta": "ሁሉንም አስጎብኚዎች ይመልከቱ",
    "cta.title": "ለሚወራ ታሪክ ዝግጁ ነዎት?",
    "cta.subtitle": "ዓለምን በነዋሪዎቹ ዓይን ያዩ በሺዎች የሚቆጠሩ ተጓዦችን ይቀላቀሉ።",
    "cta.button": "ትክክለኛውን አስጎብኚዎን ያግኙ",
    "footer.desc": "ተጓዦችን ከተረጋገጡ የአካባቢ አስጎብኚዎች ጋር በማገናኘት የተደበቁ የጉዞ ልምዶችን እናቀርባለን።",
    "footer.platform": "ፕላትፎርም",
    "footer.support": "ድጋፍ",
    "footer.rights": "© 2026 ሎካለንስ። መብቱ በህግ የተጠበቀ ነው።",
    "common.back_home": "ወደ መነሻ ተመለስ",
    "common.verified": "የተረጋገጠ",
    "common.reviews": "ግምገማዎች",
    "common.from": "ከ",
    "common.person": "ሰው",
    "common.book_now": "አሁን ይያዙ",
    "common.view_profile": "መገለጫ ይመልከቱ",
    "common.apply_guide": "አስጎብኚ ለመሆን ያመልክቱ"
  },
  GE: {
    "nav.find_guide": "იპოვე გიდი",
    "nav.world_map": "მსოფლიო რუკა",
    "nav.hidden_gems": "დამალული ადგილები",
    "nav.how_it_works": "როგორ მუშაობს",
    "nav.sign_in": "შესვლა",
    "hero.badge": "მოგზაურობის ახალი გზა",
    "hero.title.1": "იმოგზაურე როგორც ",
    "hero.title.highlight": "ადგილობრივმა",
    "hero.title.2": " და არა როგორც ტურისტმა.",
    "hero.subtitle": "დაუკავშირდით ვერიფიცირებულ ადგილობრივ გიდებს, რომლებიც გთავაზობთ უნიკალურ გამოცდილებას — ადგილებს, რომლებიც არცერთ გზამკვლევში არ წერია.",
    "hero.cta": "დაიწყე ძიება",
    "hero.social": "12 ათასზე მეტი მოგზაური უკვე ჩვენთანაა",
    "features.verified.title": "ვერიფიცირებული გიდები",
    "features.verified.desc": "თითოეული გიდი გადის პირად გასაუბრებას ადგილობრივი ცოდნის, უსაფრთხოებისა და თხრობის უნარის შესამოწმებლად.",
    "features.gems.title": "დამალული ადგილები",
    "features.gems.desc": "აღმოაჩინეთ ადგილები, რომლებიც არ არის ინსტაგრამზე ან გზამკვლევებში. ნამდვილი თავგადასავალი.",
    "features.ethical.title": "ეთიკური მოგზაურობა",
    "features.ethical.desc": "თქვენი თანხა პირდაპირ ხმარდება ადგილობრივ თემებს, კულტურული მემკვიდრეობის დაცვასა და მდგრად ტურიზმს.",
    "featured.badge": "გაიცანით ექსპერტები",
    "featured.title.1": "ჩვენი რჩეული ",
    "featured.title.highlight": "ადგილობრივი გიდები",
    "featured.title.2": "",
    "featured.cta": "ყველა გიდის ნახვა",
    "cta.title": "მზად ხართ დაუვიწყარი ისტორიისთვის?",
    "cta.subtitle": "შემოუერთდით ათასობით მოგზაურს, რომლებმაც აღმოაჩინეს მსოფლიო ადგილობრივების თვალით.",
    "cta.button": "იპოვე შენი იდეალური გიდი",
    "footer.desc": "აკავშირებს მოგზაურებს ვერიფიცირებულ ადგილობრივ გიდებთან. იმოგზაურე როგორც ადგილობრივმა.",
    "footer.platform": "პლატფორმა",
    "footer.support": "მხარდაჭერა",
    "footer.rights": "© 2026 Localens. ყველა უფლება დაცულია.",
    "common.back_home": "მთავარზე დაბრუნება",
    "common.verified": "ვერიფიცირებული",
    "common.reviews": "მიმოხილვა",
    "common.from": "დან",
    "common.person": "ადამიანი",
    "common.book_now": "დაჯავშნე ახლავე",
    "common.view_profile": "პროფილის ნახვა",
    "common.apply_guide": "გახდი გიდი"
  },
  PT: {
    "nav.find_guide": "Encontrar um Guia",
    "nav.world_map": "Mapa do Mundo",
    "nav.hidden_gems": "Tesouros Escondidos",
    "nav.how_it_works": "Como Funciona",
    "nav.sign_in": "Entrar",
    "hero.badge": "A Nova Forma de Viajar",
    "hero.title.1": "Viaje como um ",
    "hero.title.highlight": "local",
    "hero.title.2": ", não como um turista.",
    "hero.subtitle": "Conecte-se com guias locais verificados que oferecem experiências únicas — lugares, trilhas e momentos que não aparecem em nenhum guia.",
    "hero.cta": "Começar a Explorar",
    "hero.social": "Juntaram-se mais de 12k viajantes",
    "features.verified.title": "Guias Verificados",
    "features.verified.desc": "Cada guia é entrevistado pessoalmente e avaliado pelo seu conhecimento local, segurança e capacidade de contar histórias.",
    "features.gems.title": "Tesouros Escondidos",
    "features.gems.desc": "Aceda a lugares que não estão no Instagram ou em guias. Experiências autênticas fora do comum.",
    "features.ethical.title": "Viagem Ética",
    "features.ethical.desc": "O seu dinheiro vai diretamente para as comunidades locais, apoiando a preservação do património e o turismo sustentável.",
    "featured.badge": "Conheça os Especialistas",
    "featured.title.1": "Nossos ",
    "featured.title.highlight": "guias locais",
    "featured.title.2": " em destaque",
    "featured.cta": "Ver Todos os Guias",
    "cta.title": "Pronto para uma história que vale a pena contar?",
    "cta.subtitle": "Junte-se a milhares de viajantes que descobriram o mundo através dos olhos de quem o chama de lar.",
    "cta.button": "Encontre o Seu Par Perfeito",
    "footer.desc": "Conectando viajantes com guias locais verificados que oferecem experiências únicas. Viaje como um local, não como um turista.",
    "footer.platform": "Plataforma",
    "footer.support": "Suporte",
    "footer.rights": "© 2026 Localens. Todos os direitos reservados.",
    "common.back_home": "Voltar ao início",
    "common.verified": "Verificado",
    "common.reviews": "avaliações",
    "common.from": "A partir de",
    "common.person": "pessoa",
    "common.book_now": "Reservar agora",
    "common.view_profile": "Ver perfil",
    "common.apply_guide": "Candidatar-se como guia"
  },
  AR: {
    "nav.find_guide": "ابحث عن دليل",
    "nav.world_map": "خريطة العالم",
    "nav.hidden_gems": "الجواهر الخفية",
    "nav.how_it_works": "كيف يعمل",
    "nav.sign_in": "تسجيل الدخول",
    "hero.badge": "الطريقة الجديدة للسفر",
    "hero.title.1": "سافر كأنك من ",
    "hero.title.highlight": "أهل البلد",
    "hero.title.2": "، وليس كسائح.",
    "hero.subtitle": "تواصل مع أدلة محليين معتمدين يقدمون تجارب فريدة — أماكن ومسارات ولحظات لا تظهر في أي دليل سياحي.",
    "hero.cta": "ابدأ الاستكشاف",
    "hero.social": "انضم إلينا أكثر من 12 ألف مسافر",
    "features.verified.title": "أدلة معتمدون",
    "features.verified.desc": "يتم إجراء مقابلة شخصية مع كل دليل وتقييمه بناءً على معرفته المحلية وسلامته وقدرته على سرد القصص.",
    "features.gems.title": "الجواهر الخفية",
    "features.gems.desc": "الوصول إلى أماكن ليست على إنستغرام أو في الكتب السياحية. تجارب حقيقية بعيدة عن المسارات المألوفة.",
    "features.ethical.title": "سفر أخلاقي",
    "features.ethical.desc": "تذهب أموالك مباشرة إلى المجتمعات المحلية، مما يدعم الحفاظ على التراث والسياحة المستدامة.",
    "featured.badge": "قابل الخبراء",
    "featured.title.1": "",
    "featured.title.highlight": "أدلتنا المحليون",
    "featured.title.2": " المميزون",
    "featured.cta": "عرض جميع الأدلة",
    "cta.title": "جاهز لقصة تستحق السرد؟",
    "cta.subtitle": "انضم إلى آلاف المسافرين الذين اكتشفوا العالم من خلال عيون أولئك الذين يعتبرونه موطنهم.",
    "cta.button": "جد دليلك المثالي",
    "footer.desc": "ربط المسافرين بأدلة محليين معتمدين يقدمون تجارب فريدة. سافر كأنك من أهل البلد.",
    "footer.platform": "المنصة",
    "footer.support": "الدعم",
    "footer.rights": "© 2026 لوكالينز. جميع الحقوق محفوظة.",
    "common.back_home": "العودة للرئيسية",
    "common.verified": "موثق",
    "common.reviews": "تقييمات",
    "common.from": "من",
    "common.person": "شخص",
    "common.book_now": "احجز الآن",
    "common.view_profile": "عرض الملف الشخصي",
    "common.apply_guide": "تقدم لتصبح دليلاً"
  },
  SQ: {
    "nav.find_guide": "Gjej një Guida",
    "nav.world_map": "Harta e Botës",
    "nav.hidden_gems": "Thesaret e Fshehura",
    "nav.how_it_works": "Si Funksionon",
    "nav.sign_in": "Hyni",
    "hero.badge": "Mënyra e Re e Udhëtimit",
    "hero.title.1": "Udhëtoni si një ",
    "hero.title.highlight": "vendas",
    "hero.title.2": ", jo si një turist.",
    "hero.subtitle": "Lidhuni me guida lokale të verifikuara që ofrojnë përvoja unike — vende, shtigje dhe momente që nuk shfaqen në asnjë udhëzues.",
    "hero.cta": "Filloni Eksplorimin",
    "hero.social": "Bashkuar nga 12k+ udhëtarë",
    "features.verified.title": "Guida të Verifikuara",
    "features.verified.desc": "Çdo guidë intervistohet personalisht dhe vlerësohet për njohuritë lokale, sigurinë dhe aftësinë treguese.",
    "features.gems.title": "Thesaret e Fshehura",
    "features.gems.desc": "Hyni në vende që nuk janë në Instagram ose në udhëzues. Përvoja të vërteta jashtë shtigjeve të rrahura.",
    "features.ethical.title": "Udhëtim Etik",
    "features.ethical.desc": "Paratë tuaja shkojnë direkt te komunitetet lokale, duke mbështetur ruajtjen e trashëgimisë dhe turizmin e qëndrueshëm.",
    "featured.badge": "Takoni Ekspertët",
    "featured.title.1": "",
    "featured.title.highlight": "Guidat tona lokale",
    "featured.title.2": " të spikatur",
    "featured.cta": "Shiko të gjithë guidat",
    "cta.title": "Gati për një histori që ia vlen të tregohet?",
    "cta.subtitle": "Bashkohuni me mijëra udhëtarë që kanë zbuluar botën përmes syve të atyre që e quajnë atë shtëpi.",
    "cta.button": "Gjeni ndeshjen tuaj të përsosur",
    "footer.desc": "Lidhja e udhëtarëve me guida lokale të verifikuara që ofrojnë përvoja unike. Udhëtoni si një vendas.",
    "footer.platform": "Platforma",
    "footer.support": "Mbështetja",
    "footer.rights": "© 2026 Localens. Të gjitha të drejtat e rezervuara.",
    "common.back_home": "Kthehu në Fillim",
    "common.verified": "I Verifikuar",
    "common.reviews": "vlerësime",
    "common.from": "Nga",
    "common.person": "person",
    "common.book_now": "Rezervo Tani",
    "common.view_profile": "Shiko Profilin",
    "common.apply_guide": "Aplikoni për të qenë guidë"
  },
  ID: {
    "nav.find_guide": "Cari Pemandu",
    "nav.world_map": "Peta Dunia",
    "nav.hidden_gems": "Permata Tersembunyi",
    "nav.how_it_works": "Cara Kerja",
    "nav.sign_in": "Masuk",
    "hero.badge": "Cara Baru Bepergian",
    "hero.title.1": "Bepergianlah seperti penduduk ",
    "hero.title.highlight": "lokal",
    "hero.title.2": ", bukan turis.",
    "hero.subtitle": "Terhubung dengan pemandu lokal terverifikasi yang menawarkan pengalaman permata tersembunyi — tempat, jalur, and momen yang tidak muncul di buku panduan mana pun.",
    "hero.cta": "Mulai Menjelajah",
    "hero.social": "Bergabung dengan 12rb+ pelancong",
    "features.verified.title": "Pemandu Terverifikasi",
    "features.verified.desc": "Setiap pemandu diwawancarai secara pribadi dan diperiksa untuk pengetahuan lokal, keamanan, and kemampuan bercerita.",
    "features.gems.title": "Permata Tersembunyi",
    "features.gems.desc": "Akses tempat-tempat yang tidak ada di Instagram atau di buku panduan. Pengalaman luar biasa yang sesungguhnya.",
    "features.ethical.title": "Perjalanan Etis",
    "features.ethical.desc": "Uang Anda langsung disalurkan ke komunitas lokal, mendukung pelestarian warisan dan pariwisata berkelanjutan.",
    "featured.badge": "Temui Para Ahli",
    "featured.title.1": "",
    "featured.title.highlight": "Pemandu Lokal",
    "featured.title.2": " Unggulan Kami",
    "featured.cta": "Lihat Semua Pemandu",
    "cta.title": "Siap untuk cerita yang layak diceritakan?",
    "cta.subtitle": "Bergabunglah dengan ribuan pelancong yang telah menjelajahi dunia melalui mata mereka yang menyebutnya rumah.",
    "cta.button": "Temukan Pasangan Sempurna Anda",
    "footer.desc": "Menghubungkan pelancong dengan pemandu lokal terverifikasi yang menawarkan pengalaman permata tersembunyi.",
    "footer.platform": "Platform",
    "footer.support": "Dukungan",
    "footer.rights": "© 2026 Localens. Seluruh hak cipta dilindungi undang-undang.",
    "common.back_home": "Kembali ke Beranda",
    "common.verified": "Terverifikasi",
    "common.reviews": "ulasan",
    "common.from": "Mulai dari",
    "common.person": "orang",
    "common.book_now": "Pesan Sekarang",
    "common.view_profile": "Lihat Profil",
    "common.apply_guide": "Daftar jadi pemandu"
  },
  SW: {
    "nav.find_guide": "Tafuta Mwongozo",
    "nav.world_map": "Ramani ya Dunia",
    "nav.hidden_gems": "Vito Vilivyofichwa",
    "nav.how_it_works": "Jinsi Inavyofanya Kazi",
    "nav.sign_in": "Ingia",
    "hero.badge": "Njia Mpya ya Kusafiri",
    "hero.title.1": "Safiri kama ",
    "hero.title.highlight": "mwenyeji",
    "hero.title.2": ", si mtalii.",
    "hero.subtitle": "Ungana na waelekezi wa ndani walioidhinishwa ambao hutoa uzoefu wa vito vilivyofichwa — maeneo, njia, na matukio ambayo hayaonekani katika mwongozo wowote.",
    "hero.cta": "Anza Kuchunguza",
    "hero.social": "Imeunganishwa na wasafiri 12k+",
    "features.verified.title": "Waelekezi Waliothibitishwa",
    "features.verified.desc": "Kila mwongozo huhojiwa kibinafsi na kuchunguzwa kwa maarifa ya ndani, usalama, na uwezo wa kusimulia hadithi.",
    "features.gems.title": "Vito Vilivyofichwa",
    "features.gems.desc": "Fikia maeneo ambayo hayapo kwenye Instagram au kwenye miongozo. Uzoefu wa kweli nje ya njia iliyopitwa na wakati.",
    "features.ethical.title": "Usafiri wa Maadili",
    "features.ethical.desc": "Pesa zako huenda moja kwa moja kwa jamii za mahali hapo, kusaidia uhifadhi wa urithi na utalii endelevu.",
    "featured.badge": "Kutana na Wataalam",
    "featured.title.1": "",
    "featured.title.highlight": "Waelekezi Wetu wa Ndani",
    "featured.title.2": " Walioangaziwa",
    "featured.cta": "Tazama Waelekezi Wote",
    "cta.title": "Uko tayari kwa hadithi inayostahili kusimuliwa?",
    "cta.subtitle": "Jiunge na maelfu ya wasafiri ambao wamegundua ulimwengu kupitia macho ya wale wanaouita nyumbani.",
    "cta.button": "Pata Mechi Yako Kamili",
    "footer.desc": "Kuunganisha wasafiri na waelekezi wa ndani walioidhinishwa ambao hutoa uzoefu wa vito vilivyofichwa.",
    "footer.platform": "Jukwaa",
    "footer.support": "Msaada",
    "footer.rights": "© 2026 Localens. Haki zote zimehifadhiwa.",
    "common.back_home": "Rudi Nyumbani",
    "common.verified": "Imethibitishwa",
    "common.reviews": "mapitio",
    "common.from": "Kutoka",
    "common.person": "mtu",
    "common.book_now": "Weka Nafasi Sasa",
    "common.view_profile": "Tazama Wasifu",
    "common.apply_guide": "Omba kuwa mwongozo"
  }
};

const currencySymbols: Record<Currency, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  GEL: "₾",
  ETB: "Br",
  COP: "$",
  ALL: "L",
  IDR: "Rp",
  TZS: "Sh"
};

const currencyRates: Record<Currency, number> = {
  USD: 1,
  EUR: 0.94,
  GBP: 0.80,
  JPY: 154,
  GEL: 2.68,
  ETB: 57,
  COP: 3900,
  ALL: 94,
  IDR: 16000,
  TZS: 2600
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("EN");
  const [currency, setCurrency] = useState<Currency>("USD");

  const t = useCallback((key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key] || translations["EN"][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  }, [language]);

  const formatPrice = useCallback((price: number) => {
    const rate = currencyRates[currency];
    const symbol = currencySymbols[currency];
    const converted = Math.round(price * rate);
    return `${symbol}${converted}`;
  }, [currency]);

  const value = useMemo(() => ({
    language,
    currency,
    setLanguage,
    setCurrency,
    t,
    formatPrice
  }), [language, currency, t, formatPrice]);

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}
