import { createContext, useContext, useState, ReactNode, useCallback, useMemo } from "react";

export type Language = "EN" | "FR" | "AR" | "ES" | "DE";
export type Currency = "USD" | "EUR" | "GBP";

interface SettingsContextType {
  language: Language;
  currency: Currency;
  setLanguage: (lang: Language) => void;
  setCurrency: (curr: Currency) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  formatPrice: (price: number) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "nav.find_guide": "Find a Guide",
    "nav.world_map": "World Map",
    "nav.hidden_gems": "Hidden Gems",
    "nav.how_it_works": "How it Works",
    "nav.sign_in": "Sign In",
    "hero.badge": "The New Way to Travel",
    "hero.title.1": "Travel like a ",
    "hero.title.highlight": "local",
    "hero.title.2": ", not a tourist.",
    "hero.subtitle": "Connect with verified local guides who offer hidden gem experiences — places, trails, and moments that don't appear in any guidebook.",
    "hero.cta": "Start Exploring",
    "hero.social": "Joined by 12k+ travellers",
    "features.verified.title": "Verified Guides",
    "features.verified.desc": "Every guide is personally interviewed and vetted for local knowledge, safety, and storytelling ability.",
    "features.gems.title": "Hidden Gems",
    "features.gems.desc": "Access places that aren't on Instagram or in guidebooks. True off-the-beaten-path experiences.",
    "features.ethical.title": "Ethical Travel",
    "features.ethical.desc": "Your money goes directly to local communities, supporting heritage preservation and sustainable tourism.",
    "featured.badge": "Meet the Experts",
    "featured.title.1": "Our Featured ",
    "featured.title.highlight": "Local Guides",
    "featured.cta": "View All Guides",
    "cta.title": "Ready for a story worth telling?",
    "cta.subtitle": "Join thousands of travellers who have discovered the world through the eyes of those who call it home.",
    "cta.button": "Find Your Perfect Match",
    "footer.desc": "Connecting travellers with verified local guides who offer hidden gem experiences. Travel like a local, not a tourist.",
    "footer.platform": "Platform",
    "footer.support": "Support",
    "footer.rights": "© 2026 Localens. All rights reserved.",
    "common.back_home": "Back to Home",
    "common.verified": "Verified",
    "common.reviews": "reviews",
    "common.from": "From",
    "common.person": "person",
    "common.book_now": "Book Now",
    "common.view_profile": "View Profile",
    "common.apply_guide": "Apply to be a guide",
    "find.title": "Where are you headed?",
    "find.subtitle": "Select a country to discover local experts who know the hidden trails and secret stories of their homeland.",
    "find.guides_count": "{count} Guides",
    "find.another_country": "Choose another country",
    "find.showing": "Showing {count} verified local experts in {country}.",
    "profile.verified": "Verified Local Expert",
    "profile.reviews": "({count} reviews)",
    "profile.from_person": "{price} / person",
    "profile.book": "Book this guide",
    "profile.about": "About your guide",
    "profile.languages": "Languages",
    "profile.experience": "Experience",
    "profile.experience_years": "{years} Years",
    "profile.expertise": "Expertise",
    "profile.promise_badge": "{name}'s Personal Guarantee",
    "profile.packages": "Curated Experiences",
    "profile.most_popular": "Most Popular",
    "profile.select_tour": "Select this tour",
    "profile.stories": "Traveller Stories",
    "profile.secure_booking": "Secure Your Experience",
    "profile.select_package": "Choose a package",
    "profile.date": "Date",
    "profile.travellers": "Travellers",
    "profile.person": "Person",
    "profile.people": "People",
    "profile.full_name": "Full Name",
    "profile.email": "Email Address",
    "profile.message": "Message to guide (optional)...",
    "profile.confirm_pay": "Confirm & Pay Securely",
    "profile.free_cancel": "Free cancellation up to 48h",
    "profile.confirmed_within": "Confirmed within 24h",
    "profile.powered_by": "Powered by Stripe",
    "help.title": "Help Centre",
    "help.subtitle": "Everything you need to know about using Localens",
    "help.still_questions": "Still have questions?",
    "help.email_us": "Email us at support@localens.com",
    "help.email_support": "Email Support",
    "footer.guide_app": "Guide Application",
    "footer.help_centre": "Help Centre",
    "footer.safety": "Safety Guidelines",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "chat.title": "AI Match Assistant",
    "chat.subtitle": "Powered by Localens AI",
    "chat.welcome": "Welcome to Localens. I'm your AI Match assistant. Describe your dream trip, and I'll find the perfect local guide to show you the hidden gems most travellers never see.",
    "chat.placeholder": "Describe your dream trip...",
    "chat.suggested.1": "Hidden gems in Lebanon",
    "chat.suggested.2": "Off the beaten path in Japan",
    "chat.suggested.3": "Ancient ruins no one visits",
    "chat.suggested.4": "Most unique guide on the platform",
    "chat.suggested.5": "I want to sleep somewhere with no WiFi",
    "gems.badge": "Undocumented",
    "gems.title.1": "Places you won't find ",
    "gems.title.highlight": "anywhere",
    "gems.title.2": " else",
    "gems.subtitle": "These are real places. They have no Instagram hashtag. They don't appear in Google's top results. The only way to reach them is through someone who lives there.",
    "gems.mystery_title": "The mystery is the point.",
    "gems.mystery_desc": "We don't provide coordinates. We don't provide names. We provide the connection to the people who hold the keys to these places.",
    "gems.cta": "Find a local guide who knows the way",
    "how.step.1.title": "Tell us where you're going",
    "how.step.1.desc": "Choose a country or describe your dream experience to our AI. Whether it's 'stargazing in a cedar forest' or 'secret medina foundries', we listen to the details.",
    "how.step.2.title": "We match you with a local",
    "how.step.2.desc": "Our AI and editorial team match you with a verified guide who knows places others don't. We prioritize deep local knowledge and storytelling ability.",
    "how.step.3.title": "Explore the hidden gems",
    "how.step.3.desc": "Your guide takes you somewhere that doesn't exist on any tourist map. No hashtags, no crowds—just you and a story worth telling.",
    "how.step.4.title": "Book securely. Travel freely.",
    "how.step.4.desc": "Pay through Localens. Free cancellation up to 48h. Guide confirmed within 24h. We handle the logistics so you can focus on the moment.",
    "how.previous": "Previous",
    "how.next": "Next",
    "how.ready": "Ready? Find your guide",
    "how.try_live": "Try it live",
    "how.search_placeholder": "e.g. 'I want to see the Milky Way in Lebanon'",
    "how.search": "Search",
    "how.all_set": "You're all set.",
    "how.all_set_desc": "Your booking is protected, your guide is ready, and your adventure is about to begin.",
    "map.title.1": "Explore the ",
    "map.title.highlight": "World",
    "map.search_placeholder": "Search a country (e.g. Japan, Lebanon)...",
    "map.active_guide": "Active Guide",
    "map.coming_soon": "Coming Soon",
    "map.coming_soon_desc": "Guide coming soon to this region.",
    "bashir.bio": "Born in the rugged mountains of Chouf, Bashir has spent two decades mapping the undocumented trails of Lebanon. He specializes in high-altitude forest ecosystems and coastal geological wonders. His deep connection to the land allows him to navigate areas that remain invisible to mainstream tourism. Bashir is a passionate advocate for environmental preservation in the Levant.",
    "bashir.promise": "I promise you will stand somewhere in Lebanon that no other tourist has visited that day.",
    "bashir.speciality": "Hidden waterfalls, sea caves, Akkar forests, stargazing",
    "bashir.tour.1.name": "The Akkar Deep Forest Expedition",
    "bashir.tour.1.included.1": "Transport",
    "bashir.tour.1.included.2": "Traditional Lunch",
    "bashir.tour.1.included.3": "Photography Tips",
    "bashir.tour.2.name": "Coastal Caves & Salt Pans",
    "bashir.tour.2.included.1": "Boat Access",
    "bashir.tour.2.included.2": "Snacks",
    "bashir.tour.2.included.3": "Local History Guide"
  },
  FR: {
    "nav.find_guide": "Trouver un guide",
    "nav.world_map": "Carte du monde",
    "nav.hidden_gems": "Trésors cachés",
    "nav.how_it_works": "Comment ça marche",
    "nav.sign_in": "Se connecter",
    "hero.badge": "La nouvelle façon de voyager",
    "hero.title.1": "Voyagez comme un ",
    "hero.title.highlight": "local",
    "hero.title.2": ", pas comme un touriste.",
    "hero.subtitle": "Connectez-vous avec des guides locaux vérifiés qui proposent des expériences uniques — des lieux, des sentiers et des moments qui ne figurent dans aucun guide.",
    "hero.cta": "Commencer l'exploration",
    "hero.social": "Rejoint par plus de 12k voyageurs",
    "features.verified.title": "Guides vérifiés",
    "features.verified.desc": "Chaque guide est personnellement interviewé et évalué pour ses connaissances locales, sa sécurité et sa capacité à raconter des histoires.",
    "features.gems.title": "Trésors cachés",
    "features.gems.desc": "Accédez à des endroits qui ne sont pas sur Instagram ou dans les guides. De véritables expériences hors des sentiers battus.",
    "features.ethical.title": "Voyage éthique",
    "features.ethical.desc": "Votre argent va directement aux communautés locales, soutenant la préservation du patrimoine et le tourisme durable.",
    "featured.badge": "Rencontrez les experts",
    "featured.title.1": "Nos ",
    "featured.title.highlight": "guides locaux",
    "featured.cta": "Voir tous les guides",
    "cta.title": "Prêt pour une histoire qui vaut la peine d'être racontée ?",
    "cta.subtitle": "Rejoignez des milliers de voyageurs qui ont découvert le monde à travers les yeux de ceux qui y vivent.",
    "cta.button": "Trouvez votre partenaire idéal",
    "footer.desc": "Connecter les voyageurs avec des guides locaux vérifiés qui proposent des expériences uniques. Voyagez comme un local, pas comme un touriste.",
    "footer.platform": "Plateforme",
    "footer.support": "Support",
    "footer.rights": "© 2026 Localens. Tous droits réservés.",
    "common.back_home": "Retour à l'accueil",
    "common.verified": "Vérifié",
    "common.reviews": "avis",
    "common.from": "À partir de",
    "common.person": "personne",
    "common.book_now": "Réserver maintenant",
    "common.view_profile": "Voir le profil",
    "common.apply_guide": "Devenir guide",
    "find.title": "Où allez-vous ?",
    "find.subtitle": "Sélectionnez un pays pour découvrir des experts locaux qui connaissent les sentiers cachés et les histoires secrètes de leur patrie.",
    "find.guides_count": "{count} Guides",
    "find.another_country": "Choisir un autre pays",
    "find.showing": "Affichage de {count} experts locaux vérifiés en {country}.",
    "profile.verified": "Expert Local Vérifié",
    "profile.reviews": "({count} avis)",
    "profile.from_person": "{price} / personne",
    "profile.book": "Réserver ce guide",
    "profile.about": "À propos de votre guide",
    "profile.languages": "Langues",
    "profile.experience": "Expérience",
    "profile.experience_years": "{years} Ans",
    "profile.expertise": "Expertise",
    "profile.promise_badge": "Garantie Personnelle de {name}",
    "profile.packages": "Expériences Curieuses",
    "profile.most_popular": "Le Plus Populaire",
    "profile.select_tour": "Sélectionner ce tour",
    "profile.stories": "Histoires de Voyageurs",
    "profile.secure_booking": "Sécurisez Votre Expérience",
    "profile.select_package": "Choisir un forfait",
    "profile.date": "Date",
    "profile.travellers": "Voyageurs",
    "profile.person": "Personne",
    "profile.people": "Personnes",
    "profile.full_name": "Nom Complet",
    "profile.email": "Adresse E-mail",
    "profile.message": "Message au guide (optionnel)...",
    "profile.confirm_pay": "Confirmer et Payer en Toute Sécurité",
    "profile.free_cancel": "Annulation gratuite jusqu'à 48h",
    "profile.confirmed_within": "Confirmé sous 24h",
    "profile.powered_by": "Sécurisé par Stripe",
    "help.title": "Centre d'Aide",
    "help.subtitle": "Tout ce que vous devez savoir sur l'utilisation de Localens",
    "help.still_questions": "Vous avez encore des questions ?",
    "help.email_us": "Envoyez-nous un e-mail à support@localens.com",
    "help.email_support": "Support par E-mail",
    "footer.guide_app": "Candidature Guide",
    "footer.help_centre": "Centre d'Aide",
    "footer.safety": "Consignes de Sécurité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.privacy": "Politique de Confidentialité",
    "chat.title": "Assistant de Match IA",
    "chat.subtitle": "Propulsé par Localens IA",
    "chat.welcome": "Bienvenue chez Localens. Je suis votre assistant de match IA. Décrivez votre voyage de rêve, et je trouverai le guide local parfait pour vous montrer les joyaux cachés que la plupart des voyageurs ne voient jamais.",
    "chat.placeholder": "Décrivez votre voyage de rêve...",
    "chat.suggested.1": "Joyaux cachés au Liban",
    "chat.suggested.2": "Hors des sentiers battus au Japon",
    "chat.suggested.3": "Ruines antiques que personne ne visite",
    "chat.suggested.4": "Guide le plus unique sur la plateforme",
    "chat.suggested.5": "Je veux dormir quelque part sans WiFi",
    "gems.badge": "Non documenté",
    "gems.title.1": "Des endroits que vous ne trouverez ",
    "gems.title.highlight": "nulle part",
    "gems.title.2": " ailleurs",
    "gems.subtitle": "Ce sont de vrais endroits. Ils n'ont pas de hashtag Instagram. Ils n'apparaissent pas dans les meilleurs résultats de Google. La seule façon de les atteindre est de passer par quelqu'un qui y vit.",
    "gems.mystery_title": "Le mystère est le but.",
    "gems.mystery_desc": "Nous ne fournissons pas de coordonnées. Nous ne fournissons pas de noms. Nous fournissons la connexion aux personnes qui détiennent les clés de ces lieux.",
    "gems.cta": "Trouver un guide local qui connaît le chemin",
    "how.step.1.title": "Dites-nous où vous allez",
    "how.step.1.desc": "Choisissez un pays ou décrivez votre expérience de rêve à notre IA. Qu'il s'agisse d'observer les étoiles dans une forêt de cèdres ou de découvrir des fonderies secrètes dans la médina, nous écoutons les détails.",
    "how.step.2.title": "Nous vous mettons en relation avec un local",
    "how.step.2.desc": "Notre IA et notre équipe éditoriale vous mettent en relation avec un guide vérifié qui connaît des endroits que les autres ignorent. Nous privilégions une connaissance locale approfondie et une capacité de narration.",
    "how.step.3.title": "Explorez les joyaux cachés",
    "how.step.3.desc": "Votre guide vous emmène dans un endroit qui n'existe sur aucune carte touristique. Pas de hashtags, pas de foules — juste vous et une histoire qui vaut la peine d'être racontée.",
    "how.step.4.title": "Réservez en toute sécurité. Voyagez librement.",
    "how.step.4.desc": "Payez via Localens. Annulation gratuite jusqu'à 48h. Guide confirmé sous 24h. Nous gérons la logistique pour que vous puissiez vous concentrer sur le moment présent.",
    "how.previous": "Précédent",
    "how.next": "Suivant",
    "how.ready": "Prêt ? Trouvez votre guide",
    "how.try_live": "Essayez-le en direct",
    "how.search_placeholder": "ex: 'Je veux voir la Voie Lactée au Liban'",
    "how.search": "Rechercher",
    "how.all_set": "Vous êtes prêt.",
    "how.all_set_desc": "Votre réservation est protégée, votre guide est prêt et votre aventure est sur le point de commencer.",
    "map.title.1": "Explorez le ",
    "map.title.highlight": "Monde",
    "map.search_placeholder": "Rechercher un pays (ex: Japon, Liban)...",
    "map.active_guide": "Guide Actif",
    "map.coming_soon": "Bientôt Disponible",
    "map.coming_soon_desc": "Guide bientôt disponible dans cette région.",
    "bashir.bio": "Né dans les montagnes escarpées du Chouf, Bashir a passé deux décennies à cartographier les sentiers non documentés du Liban. Il se spécialise dans les écosystèmes forestiers de haute altitude et les merveilles géologiques côtières. Son lien profond avec la terre lui permet de naviguer dans des zones qui restent invisibles pour le tourisme grand public. Bashir est un fervent défenseur de la préservation de l'environnement au Levant.",
    "bashir.promise": "Je vous promets que vous vous tiendrez quelque part au Liban qu'aucun autre touriste n'aura visité ce jour-là.",
    "bashir.speciality": "Cascades cachées, grottes marines, forêts du Akkar, observation des étoiles",
    "bashir.tour.1.name": "L'expédition en forêt profonde du Akkar",
    "bashir.tour.1.included.1": "Transport",
    "bashir.tour.1.included.2": "Déjeuner traditionnel",
    "bashir.tour.1.included.3": "Conseils en photographie",
    "bashir.tour.2.name": "Grottes côtières et marais salants",
    "bashir.tour.2.included.1": "Accès en bateau",
    "bashir.tour.2.included.2": "Collations",
    "bashir.tour.2.included.3": "Guide d'histoire locale"
  },
  ES: {
    "nav.find_guide": "Buscar un guía",
    "nav.world_map": "Mapa mundial",
    "nav.hidden_gems": "Joyas ocultas",
    "nav.how_it_works": "Cómo funciona",
    "nav.sign_in": "Iniciar sesión",
    "hero.badge": "La nueva forma de viajar",
    "hero.title.1": "Viaja como un ",
    "hero.title.highlight": "local",
    "hero.title.2": ", no como un turista.",
    "hero.subtitle": "Conéctate con guías locales verificados que ofrecen experiencias únicas: lugares, senderos y momentos que no aparecen en ninguna guía.",
    "hero.cta": "Empezar a explorar",
    "hero.social": "Se han unido más de 12k viajeros",
    "features.verified.title": "Guías verificados",
    "features.verified.desc": "Cada guía es entrevistado personalmente y evaluado por su conocimiento local, seguridad y capacidad narrativa.",
    "features.gems.title": "Joyas ocultas",
    "features.gems.desc": "Accede a lugares que no están en Instagram ni en las guías. Experiencias auténticas fuera de lo común.",
    "features.ethical.title": "Viaje ético",
    "features.ethical.desc": "Tu dinero va directamente a las comunidades locales, apoyando la preservación del patrimonio y el turismo sostenible.",
    "featured.badge": "Conoce a los expertos",
    "featured.title.1": "Nuestros ",
    "featured.title.highlight": "guías locales",
    "featured.cta": "Ver todos los guías",
    "cta.title": "¿Listo para una historia que valga la pena contar?",
    "cta.subtitle": "Únete a miles de viajeros que han descubierto el mundo a través de los ojos de quienes lo llaman hogar.",
    "cta.button": "Encuentra tu pareja ideal",
    "footer.desc": "Conectando viajeros con guías locales verificados que ofrecen experiencias únicas. Viaja como un local, no como un turista.",
    "footer.platform": "Plataforma",
    "footer.support": "Soporte",
    "footer.rights": "© 2026 Localens. Todos los derechos reservados.",
    "common.back_home": "Volver al inicio",
    "common.verified": "Verificado",
    "common.reviews": "reseñas",
    "common.from": "Desde",
    "common.person": "persona",
    "common.book_now": "Reservar ahora",
    "common.view_profile": "Ver perfil",
    "common.apply_guide": "Postular como guía",
    "chat.title": "Asistente de IA",
    "chat.subtitle": "Tu guía local de IA",
    "chat.welcome": "¡Hola! Soy tu asistente de IA de Localens. Puedo ayudarte a encontrar el guía perfecto o descubrir joyas ocultas. ¿A dónde te gustaría ir?",
    "chat.placeholder": "Pregúntame cualquier cosa...",
    "chat.suggested.1": "¿Quién es el mejor guía para el Líbano?",
    "chat.suggested.2": "Encuéntrame una joya oculta en Japón",
    "chat.suggested.3": "¿Cómo funciona Localens?",
    "chat.suggested.4": "Muéstrame guías en Marruecos",
    "chat.suggested.5": "¿Qué incluye el tour de Bashir?",
    "gems.badge": "No documentado",
    "gems.title.1": "Lugares que no encontrarás en ",
    "gems.title.highlight": "ningún otro",
    "gems.title.2": " lugar",
    "gems.subtitle": "Estos son lugares reales. No tienen hashtag en Instagram. No aparecen en los primeros resultados de Google. La única forma de llegar a ellos es a través de alguien que viva allí.",
    "gems.mystery_title": "El misterio es el punto.",
    "gems.mystery_desc": "No proporcionamos coordenadas. No proporcionamos nombres. Proporcionamos la conexión con las personas que tienen las llaves de estos lugares.",
    "gems.cta": "Encuentra un guía local que conozca el camino",
    "how.step.1.title": "Cuéntanos a dónde vas",
    "how.step.1.desc": "Elige un país o describe tu experiencia soñada a nuestra IA. Ya sea 'observar estrellas en un bosque de cedros' o 'fundiciones secretas en la medina', escuchamos los detalles.",
    "how.step.2.title": "Te emparejamos con un local",
    "how.step.2.desc": "Nuestro equipo editorial y de IA te empareja con un guía verificado que conoce lugares que otros no. Priorizamos el conocimiento local profundo y la capacidad narrativa.",
    "how.step.3.title": "Explora las joyas ocultas",
    "how.step.3.desc": "Tu guía te lleva a algún lugar que no existe en ningún mapa turístico. Sin hashtags, sin multitudes, solo tú y una historia que vale la pena contar.",
    "how.step.4.title": "Reserva de forma segura. Viaja libremente.",
    "how.step.4.desc": "Paga a través de Localens. Cancelación gratuita hasta 48h. Guía confirmado en 24h. Nosotros nos encargamos de la logística para que tú te enfoques en el momento.",
    "how.previous": "Anterior",
    "how.next": "Siguiente",
    "how.ready": "¿Listo? Encuentra tu guía",
    "how.try_live": "Pruébalo en vivo",
    "how.search_placeholder": "ej. 'Quiero ver la Vía Láctea en el Líbano'",
    "how.search": "Buscar",
    "how.all_set": "Todo listo.",
    "how.all_set_desc": "Tu reserva está protegida, tu guía está listo y tu aventura está a punto de comenzar.",
    "map.title.1": "Explora el ",
    "map.title.highlight": "Mundo",
    "map.search_placeholder": "Busca un país (ej. Japón, Líbano)...",
    "map.active_guide": "Guía Activo",
    "map.coming_soon": "Próximamente",
    "map.coming_soon_desc": "Guía próximamente en esta región.",
    "bashir.bio": "Nacido en las escarpadas montañas de Chouf, Bashir ha pasado dos décadas mapeando los senderos no documentados del Líbano. Se especializa en ecosistemas forestales de gran altitud y maravillas geológicas costeras. His profunda conexión con la tierra le permite navegar por áreas que permanecen invisibles para el turismo convencional. Bashir es un apasionado defensor de la preservación del medio ambiente en el Levante.",
    "bashir.promise": "Te prometo que estarás en algún lugar del Líbano que ningún otro turista haya visitado ese día.",
    "bashir.speciality": "Cascadas ocultas, cuevas marinas, bosques de Akkar, observación de estrellas",
    "bashir.tour.1.name": "La expedición al bosque profundo de Akkar",
    "bashir.tour.1.included.1": "Transporte",
    "bashir.tour.1.included.2": "Almuerzo tradicional",
    "bashir.tour.1.included.3": "Consejos de fotografía",
    "bashir.tour.2.name": "Cuevas costeras y salinas",
    "bashir.tour.2.included.1": "Acceso en barco",
    "bashir.tour.2.included.2": "Aperitivos",
    "bashir.tour.2.included.3": "Guía de historia local"
  },
  DE: {
    "nav.find_guide": "Guide finden",
    "nav.world_map": "Weltkarte",
    "nav.hidden_gems": "Geheimtipps",
    "nav.how_it_works": "So funktioniert's",
    "nav.sign_in": "Anmelden",
    "hero.badge": "Die neue Art zu reisen",
    "hero.title.1": "Reise wie ein ",
    "hero.title.highlight": "Einheimischer",
    "hero.title.2": ", nicht wie ein Tourist.",
    "hero.subtitle": "Verbinden Sie sich mit verifizierten lokalen Guides, die versteckte Erlebnisse bieten – Orte, Pfade und Momente, die in keinem Reiseführer stehen.",
    "hero.cta": "Erkundung starten",
    "hero.social": "Über 12.000 Reisende sind dabei",
    "features.verified.title": "Verifizierte Guides",
    "features.verified.desc": "Jeder Guide wird persönlich interviewt und auf lokales Wissen, Sicherheit und Erzähltalent geprüft.",
    "features.gems.title": "Geheimtipps",
    "features.gems.desc": "Besuchen Sie Orte, die nicht auf Instagram oder in Reiseführern stehen. Echte Erlebnisse abseits der ausgetretenen Pfade.",
    "features.ethical.title": "Ethisches Reisen",
    "features.ethical.desc": "Ihr Geld geht direkt an lokale Gemeinschaften und unterstützt den Erhalt des Erbes und nachhaltigen Tourismus.",
    "featured.badge": "Treffen Sie die Experten",
    "featured.title.1": "Unsere vorgestellten ",
    "featured.title.highlight": "lokalen Guides",
    "featured.cta": "Alle Guides ansehen",
    "cta.title": "Bereit für eine Geschichte, die es wert ist, erzählt zu werden?",
    "cta.subtitle": "Schließen Sie sich Tausenden von Reisenden an, die die Welt durch die Augen derer entdeckt haben, die sie ihr Zuhause nennen.",
    "cta.button": "Finden Sie Ihren perfekten Partner",
    "footer.desc": "Verbindet Reisende mit verifizierten lokalen Guides, die versteckte Erlebnisse bieten. Reisen Sie wie ein Einheimischer.",
    "footer.platform": "Plattform",
    "footer.support": "Support",
    "footer.rights": "© 2026 Localens. Alle Rechte vorbehalten.",
    "common.back_home": "Zurück zur Startseite",
    "common.verified": "Verifiziert",
    "common.reviews": "Bewertungen",
    "common.from": "Ab",
    "common.person": "Person",
    "common.book_now": "Jetzt buchen",
    "common.view_profile": "Profil ansehen",
    "common.apply_guide": "Als Guide bewerben",
    "find.title": "Wohin geht die Reise?",
    "find.subtitle": "Wählen Sie ein Land, um lokale Experten zu entdecken, die die verborgenen Pfade und geheimen Geschichten ihrer Heimat kennen.",
    "find.guides_count": "{count} Guides",
    "find.another_country": "Anderes Land wählen",
    "find.showing": "Zeige {count} verifizierte lokale Experten in {country}.",
    "profile.verified": "Verifizierter lokaler Experte",
    "profile.reviews": "({count} Bewertungen)",
    "profile.from_person": "{price} / Person",
    "profile.book": "Diesen Guide buchen",
    "profile.about": "Über Ihren Guide",
    "profile.languages": "Sprachen",
    "profile.experience": "Erfahrung",
    "profile.experience_years": "{years} Jahre",
    "profile.expertise": "Fachwissen",
    "profile.promise_badge": "{name}s persönliche Garantie",
    "profile.packages": "Kuratierte Erlebnisse",
    "profile.most_popular": "Beliebteste",
    "profile.select_tour": "Diese Tour wählen",
    "profile.stories": "Reisegeschichten",
    "profile.secure_booking": "Sichern Sie Ihr Erlebnis",
    "profile.select_package": "Paket wählen",
    "profile.date": "Datum",
    "profile.travellers": "Reisende",
    "profile.person": "Person",
    "profile.people": "Personen",
    "profile.full_name": "Vollständiger Name",
    "profile.email": "E-Mail-Adresse",
    "profile.message": "Nachricht an den Guide (optional)...",
    "profile.confirm_pay": "Bestätigen & sicher bezahlen",
    "profile.free_cancel": "Kostenlose Stornierung bis 48h",
    "profile.confirmed_within": "Bestätigt innerhalb von 24h",
    "profile.powered_by": "Unterstützt von Stripe",
    "help.title": "Hilfezentrum",
    "help.subtitle": "Alles, was Sie über die Nutzung von Localens wissen müssen",
    "help.still_questions": "Haben Sie noch Fragen?",
    "help.email_us": "Schreiben Sie uns an support@localens.com",
    "help.email_support": "E-Mail-Support",
    "footer.guide_app": "Guide-Bewerbung",
    "footer.help_centre": "Hilfezentrum",
    "footer.safety": "Sicherheitsrichtlinien",
    "footer.terms": "Nutzungsbedingungen",
    "footer.privacy": "Datenschutzrichtlinie",
    "chat.title": "KI-Match-Assistent",
    "chat.subtitle": "Unterstützt von Localens KI",
    "chat.welcome": "Willkommen bei Localens. Ich bin Ihr KI-Match-Assistent. Beschreiben Sie Ihre Traumreise, und I finde den perfekten lokalen Guide, der Ihnen die verborgenen Schätze zeigt, die die meisten Reisenden nie sehen.",
    "chat.placeholder": "Beschreiben Sie Ihre Traumreise...",
    "chat.suggested.1": "Geheimtipps im Libanon",
    "chat.suggested.2": "Abseits der Pfade in Japan",
    "chat.suggested.3": "Alte Ruinen, die niemand besucht",
    "chat.suggested.4": "Einzigartigster Guide auf der Plattform",
    "chat.suggested.5": "Ich möchte irgendwo ohne WLAN schlafen",
    "gems.badge": "Undokumentiert",
    "gems.title.1": "Orte, die Sie ",
    "gems.title.highlight": "nirgendwo",
    "gems.title.2": " sonst finden",
    "gems.subtitle": "Dies sind echte Orte. Sie haben keinen Instagram-Hashtag. Sie erscheinen nicht in den Top-Ergebnissen von Google. Der einzige Weg, sie zu erreichen, führt über jemanden, der dort lebt.",
    "gems.mystery_title": "Das Geheimnis ist der Punkt.",
    "gems.mystery_desc": "Wir geben keine Koordinaten an. Wir geben keine Namen an. Wir bieten die Verbindung zu den Menschen, die die Schlüssel zu diesen Orten halten.",
    "gems.cta": "Finden Sie einen lokalen Guide, der den Weg kennt",
    "how.step.1.title": "Sagen Sie uns, wohin Sie reisen",
    "how.step.1.desc": "Wählen Sie ein Land oder beschreiben Sie Ihr Traumerlebnis unserer KI. Ob 'Sternenbeobachtung in einem Zedernwald' oder 'geheime Medina-Gießereien', wir hören auf die Details.",
    "how.step.2.title": "Wir vermitteln Ihnen einen Einheimischen",
    "how.step.2.desc": "Unser KI- und Redaktionsteam vermittelt Ihnen einen verifizierten Guide, der Orte kennt, die andere nicht kennen. Wir priorisieren tiefes lokales Wissen und Erzähltalent.",
    "how.step.3.title": "Erkunden Sie die Geheimtipps",
    "how.step.3.desc": "Ihr Guide führt Sie an einen Ort, der auf keiner Touristenkarte existiert. Keine Hashtags, keine Menschenmassen – nur Sie und eine Geschichte, die es wert ist, erzählt zu werden.",
    "how.step.4.title": "Sicher buchen. Frei reisen.",
    "how.step.4.desc": "Bezahlen Sie über Localens. Kostenlose Stornierung bis 48h. Guide-Bestätigung innerhalb von 24h. Wir kümmern uns um die Logistik, damit Sie sich auf den Moment konzentrieren können.",
    "how.previous": "Zurück",
    "how.next": "Weiter",
    "how.ready": "Bereit? Finden Sie Ihren Guide",
    "how.try_live": "Live ausprobieren",
    "how.search_placeholder": "z.B. 'Ich möchte die Milchstraße im Libanon sehen'",
    "how.search": "Suchen",
    "how.all_set": "Alles bereit.",
    "how.all_set_desc": "Ihre Buchung ist geschützt, Ihr Guide ist bereit und Ihr Abenteuer kann beginnen.",
    "map.title.1": "Erkunden Sie die ",
    "map.title.highlight": "Welt",
    "map.search_placeholder": "Land suchen (z.B. Japan, Libanon)...",
    "map.active_guide": "Aktiver Guide",
    "map.coming_soon": "Demnächst",
    "map.coming_soon_desc": "Guides für diese Region folgen in Kürze.",
    "bashir.bio": "Bashir wurde in den schroffen Bergen von Chouf geboren und hat zwei Jahrzehnte damit verbracht, die undokumentierten Pfade des Libanon zu kartieren. Er ist spezialisiert auf Hochgebirgswald-Ökosysteme und geologische Wunder an der Küste. Seine tiefe Verbindung zum Land ermöglicht es ihm, Gebiete zu befahren, die für den Mainstream-Tourismus unsichtbar bleiben. Bashir ist ein leidenschaftlicher Verfechter des Umweltschutzes in der Levante.",
    "bashir.promise": "Ich verspreche Ihnen, dass Sie an einem Ort im Libanon stehen werden, den an diesem Tag kein anderer Tourist besucht hat.",
    "bashir.speciality": "Versteckte Wasserfälle, Meereshöhlen, Akkar-Wälder, Sternenbeobachtung",
    "bashir.tour.1.name": "Die Akkar-Tiefwald-Expedition",
    "bashir.tour.1.included.1": "Transport",
    "bashir.tour.1.included.2": "Traditionelles Mittagessen",
    "bashir.tour.1.included.3": "Fotografie-Tipps",
    "bashir.tour.2.name": "Küstenhöhlen & Salzpfannen",
    "bashir.tour.2.included.1": "Bootszugang",
    "bashir.tour.2.included.2": "Snacks",
    "bashir.tour.2.included.3": "Lokaler Geschichtsführer"
  },
  AR: {
    "nav.find_guide": "ابحث عن دليل",
    "nav.world_map": "خريطة العالم",
    "nav.hidden_gems": "الجواهر الخفية",
    "nav.how_it_works": "كيف يعمل",
    "nav.sign_in": "تسجيل الدخول",
    "hero.badge": "الطريقة الجديدة للسفر",
    "hero.title.1": "سافر كأنك من ",
    "hero.title.highlight": "أهل البلد",
    "hero.title.2": "، وليس كسائح.",
    "hero.subtitle": "تواصل مع أدلة محليين معتمدين يقدمون تجارب فريدة — أماكن ومسارات ولحظات لا تظهر في أي دليل سياحي.",
    "hero.cta": "ابدأ الاستكشاف",
    "hero.social": "انضم إلينا أكثر من 12 ألف مسافر",
    "features.verified.title": "أدلة معتمدون",
    "features.verified.desc": "يتم إجراء مقابلة شخصية مع كل دليل وتقييمه بناءً على معرفته المحلية وسلامته وقدرته على سرد القصص.",
    "features.gems.title": "الجواهر الخفية",
    "features.gems.desc": "الوصول إلى أماكن ليست على إنستغرام أو في الكتب السياحية. تجارب حقيقية بعيدة عن المسارات المألوفة.",
    "features.ethical.title": "سفر أخلاقي",
    "features.ethical.desc": "تذهب أموالك مباشرة إلى المجتمعات المحلية، مما يدعم الحفاظ على التراث والسياحة المستدامة.",
    "featured.badge": "قابل الخبراء",
    "featured.title.1": "",
    "featured.title.highlight": "أدلتنا المحليون",
    "featured.cta": "عرض جميع الأدلة",
    "cta.title": "جاهز لقصة تستحق السرد؟",
    "cta.subtitle": "انضم إلى آلاف المسافرين الذين اكتشفوا العالم من خلال عيون أولئك الذين يعتبرونه موطنهم.",
    "cta.button": "جد دليلك المثالي",
    "footer.desc": "ربط المسافرين بأدلة محليين معتمدين يقدمون تجارب فريدة. سافر كأنك من أهل البلد.",
    "footer.platform": "المنصة",
    "footer.support": "الدعم",
    "footer.rights": "© 2026 لوكالينز. جميع الحقوق محفوظة.",
    "common.back_home": "العودة للرئيسية",
    "common.verified": "موثق",
    "common.reviews": "تقييمات",
    "common.from": "من",
    "common.person": "شخص",
    "common.book_now": "احجز الآن",
    "common.view_profile": "عرض الملف الشخصي",
    "common.apply_guide": "تقدم لتصبح دليلاً",
    "find.title": "إلى أين تتجه؟",
    "find.subtitle": "اختر بلداً لاكتشاف الخبراء المحليين الذين يعرفون المسارات الخفية والقصص السرية لوطنهم.",
    "find.guides_count": "{count} أدلة",
    "find.another_country": "اختر بلداً آخر",
    "find.showing": "عرض {count} من الخبراء المحليين المعتمدين في {country}.",
    "profile.verified": "خبير محلي معتمد",
    "profile.reviews": "({count} تقييمات)",
    "profile.from_person": "{price} / للشخص",
    "profile.book": "احجز هذا الدليل",
    "profile.about": "عن دليلك",
    "profile.languages": "اللغات",
    "profile.experience": "الخبرة",
    "profile.experience_years": "{years} سنوات",
    "profile.expertise": "التخصص",
    "profile.promise_badge": "ضمان {name} الشخصي",
    "profile.packages": "تجارب مختارة",
    "profile.most_popular": "الأكثر شعبية",
    "profile.select_tour": "اختر هذه الجولة",
    "profile.stories": "قصص المسافرين",
    "profile.secure_booking": "أمن تجربتك",
    "profile.select_package": "اختر باقة",
    "profile.date": "التاريخ",
    "profile.travellers": "المسافرون",
    "profile.person": "شخص",
    "profile.people": "أشخاص",
    "profile.full_name": "الاسم الكامل",
    "profile.email": "البريد الإلكتروني",
    "profile.message": "رسالة للدليل (اختياري)...",
    "profile.confirm_pay": "تأكيد والدفع بأمان",
    "profile.free_cancel": "إلغاء مجاني حتى 48 ساعة",
    "profile.confirmed_within": "يتم التأكيد خلال 24 ساعة",
    "profile.powered_by": "بواسطة Stripe",
    "help.title": "مركز المساعدة",
    "help.subtitle": "كل ما تحتاج لمعرفته حول استخدام Localens",
    "help.still_questions": "لا تزال لديك أسئلة؟",
    "help.email_us": "راسلنا على support@localens.com",
    "help.email_support": "دعم البريد الإلكتروني",
    "footer.guide_app": "طلب الانضمام كدليل",
    "footer.help_centre": "مركز المساعدة",
    "footer.safety": "إرشادات السلامة",
    "footer.terms": "شروط الخدمة",
    "footer.privacy": "سياسة الخصوصية",
    "chat.title": "مساعد التوفيق الذكي",
    "chat.subtitle": "مدعوم بذكاء Localens",
    "chat.welcome": "مرحباً بك في Localens. أنا مساعدك الذكي. صف رحلة أحلامك، وسأجد لك الدليل المحلي المثالي ليريك الجواهر الخفية التي لا يراها معظم المسافرين.",
    "chat.placeholder": "صف رحلة أحلامك...",
    "chat.suggested.1": "جواهر خفية في لبنان",
    "chat.suggested.2": "بعيداً عن المسارات المألوفة في اليابان",
    "chat.suggested.3": "أطلال قديمة لا يزورها أحد",
    "chat.suggested.4": "أكثر دليل تميزاً على المنصة",
    "chat.suggested.5": "أريد النوم في مكان بدون واي فاي",
    "gems.badge": "غير موثق",
    "gems.title.1": "أماكن لن تجدها في ",
    "gems.title.highlight": "أي مكان",
    "gems.title.2": " آخر",
    "gems.subtitle": "هذه أماكن حقيقية. ليس لها وسم على إنستغرام. لا تظهر في نتائج جوجل الأولى. الطريقة الوحيدة للوصول إليها هي من خلال شخص يعيش هناك.",
    "gems.mystery_title": "الغموض هو الهدف.",
    "gems.mystery_desc": "نحن لا نقدم إحداثيات. نحن لا نقدم أسماء. نحن نقدم التواصل مع الأشخاص الذين يملكون مفاتيح هذه الأماكن.",
    "gems.cta": "جد دليلاً محلياً يعرف الطريق",
    "how.step.1.title": "أخبرنا إلى أين أنت ذاهب",
    "how.step.1.desc": "اختر بلداً أو صف تجربة أحلامك لذكائنا الاصطناعي. سواء كان ذلك 'مراقبة النجوم في غابة أرز' أو 'مسابك المدينة السرية'، نحن نستمع للتفاصيل.",
    "how.step.2.title": "نوفقك مع شخص محلي",
    "how.step.2.desc": "يقوم فريقنا وذكاؤنا الاصطناعي بتوفيقك مع دليل معتمد يعرف أماكن لا يعرفها الآخرون. نحن نعطي الأولوية للمعرفة المحلية العميقة والقدرة على سرد القصص.",
    "how.step.3.title": "استكشف الجواهر الخفية",
    "how.step.3.desc": "يأخذك دليلك إلى مكان لا يوجد على أي خريطة سياحية. لا وسوم، لا زحام — فقط أنت وقصة تستحق السرد.",
    "how.step.4.title": "احجز بأمان. سافر بحرية.",
    "how.step.4.desc": "ادفع من خلال Localens. إلغاء مجاني حتى 48 ساعة. يتم تأكيد الدليل خلال 24 ساعة. نحن نتولى الخدمات اللوجستية حتى تتمكن من التركيز على اللحظة.",
    "how.previous": "السابق",
    "how.next": "التالي",
    "how.ready": "جاهز؟ جد دليلك",
    "how.try_live": "جربه مباشرة",
    "how.search_placeholder": "مثلاً: 'أريد رؤية درب التبانة في لبنان'",
    "how.search": "بحث",
    "how.all_set": "أنت جاهز تماماً.",
    "how.all_set_desc": "حجزك محمي، ودليلك جاهز، ومغامرتك على وشك البدء.",
    "map.title.1": "استكشف ",
    "map.title.highlight": "العالم",
    "map.search_placeholder": "ابحث عن بلد (مثلاً: اليابان، لبنان)...",
    "map.active_guide": "دليل نشط",
    "map.coming_soon": "قريباً",
    "map.coming_soon_desc": "دليل قادم قريباً لهذه المنطقة.",
    "bashir.bio": "ولد بشير في جبال الشوف الوعرة، وأمضى عقدين من الزمن في رسم خرائط المسارات غير الموثقة في لبنان. يتخصص في النظم البيئية للغابات على ارتفاعات عالية والعجائب الجيولوجية الساحلية. يسمح له ارتباطه العميق بالأرض بالتنقل في مناطق تظل غير مرئية للسياحة السائدة. بشير مدافع شغوف عن الحفاظ على البيئة في بلاد الشام.",
    "bashir.promise": "أعدك بأنك ستقف في مكان ما في لبنان لم يزره أي سائح آخر في ذلك اليوم.",
    "bashir.speciality": "شلالات خفية، كهوف بحرية، غابات عكار، مراقبة النجوم",
    "bashir.tour.1.name": "رحلة غابة عكار العميقة",
    "bashir.tour.1.included.1": "النقل",
    "bashir.tour.1.included.2": "غداء تقليدي",
    "bashir.tour.1.included.3": "نصائح التصوير الفوتوغرافي",
    "bashir.tour.2.name": "الكهوف الساحلية وأحواض الملح",
    "bashir.tour.2.included.1": "وصول بالقارب",
    "bashir.tour.2.included.2": "وجبات خفيفة",
    "bashir.tour.2.included.3": "دليل التاريخ المحلي"
  }
};

const currencySymbols: Record<Currency, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£"
};

const currencyRates: Record<Currency, number> = {
  USD: 1,
  EUR: 0.94,
  GBP: 0.80
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("EN");
  const [currency, setCurrency] = useState<Currency>("USD");

  const t = useCallback((key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key] || translations["EN"][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  }, [language]);

  const formatPrice = useCallback((price: number) => {
    const rate = currencyRates[currency];
    const symbol = currencySymbols[currency];
    const converted = Math.round(price * rate);
    return `${symbol}${converted}`;
  }, [currency]);

  const value = useMemo(() => ({
    language,
    currency,
    setLanguage,
    setCurrency,
    t,
    formatPrice
  }), [language, currency, t, formatPrice]);

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}
